/**
 * Client-safe Puck config for the EDITOR canvas.
 *
 * The gallery blocks are now ISOMORPHIC (client-safe) — they render their own
 * `images[]` prop with no DB access. The editor uses the REAL component for
 * true WYSIWYG. All content/layout editing flows through StyleToolkitField.
 *
 * FeaturedWork is now ISOMORPHIC — the editor renders the real component for true
 * WYSIWYG. ContactDetails remains server-only; the editor renders a lightweight Preview.
 *
 * The Video block and the manual primitives (Heading/Text/Image/Button/Spacer/
 * Divider/Columns/Container) are ISOMORPHIC (client-safe), so the editor renders
 * the REAL component and only swaps in editor-friendly fields (StyleToolkit).
 * Their defaultProps are imported directly to guarantee
 * parity.
 *
 * The 33 preset blocks (11 groups x 3 variants — see SECTION_PRESETS in
 * blocks/sectionPresets.ts) are Container-based compositions, generated by
 * looping the registry. They render the REAL ContainerBlock with editor-friendly
 * container fields (style picker + background controls). Their defaultProps
 * come from SECTION_PRESETS.
 *
 * Component `type` keys + field keys MUST match `puckConfig` exactly so data
 * round-trips. A test (editorConfig.test.ts) guards parity.
 *
 * Editor chrome is fully localized (Phase D). All block labels, category titles,
 * field labels, and option labels are translated via createEditorConfig(t).
 * Puck built-in UI strings (drag handles, empty-slot placeholder, "Insert" drawer
 * header) cannot be localized through Puck's public API — see Phase D report.
 */

import type { Config, ComponentConfig, Field, Fields } from "@measured/puck";
import { MultiImageControl } from "./galleryPicker/MediaField";
import type { MediaPickerSelection } from "./galleryPicker/MediaPicker";
import { StyleToolkitField, type NavDetachContext } from "./StyleToolkitField";
import { useChromeSync } from "./chromeSyncContext";
import type { ZoneKey } from "./chromeSync";
import { RootStyleField } from "./RootStyleField";
import type { RootPageStyle } from "./rootStyle";
import { NumberInputRow } from "./toolbarPrimitives";
import {
  resolveBlockStyle,
  resolveBlockAttrs,
  buildContactLabelStyle,
  buildContactValueStyle,
  buildContactIconColor,
  buildContactIconSize,
  buildContactIconAlign,
  contactGridTemplate,
  type BlockStyle,
  type StyleColorToken,
} from "./styleToolkit";
import { SocialIconLink } from "./blocks/SocialIconLink";
import { MANUAL_BLOCK_KEYS } from "./blockCategories";
// Preset registry — single source for the 33 preset component configs + the
// 11 grouped drawer categories.
import {
  SECTION_PRESETS,
  SECTION_PRESET_KEYS,
  NAV_PRESET_KEYS,
  PRESET_GROUPS,
  type SectionPresetKey,
} from "./blocks/sectionPresets";
import {
  NavigationBlock,
  navigationDefaultProps,
  navigationFields,
  navigationPermissions,
  type NavigationBlockProps,
} from "./blocks/NavigationBlock";
// Data blocks are SERVER modules (Mongo / node:async_hooks). Import their TYPES
// only — their value defaultProps are inlined below so this CLIENT config never
// drags the server graph into the editor bundle (that breaks the build).
// normalizeSocialUrl is a pure utility with no server-only deps — safe to import.
import { normalizeSocialUrl, type ContactDetailsProps } from "./blocks/ContactDetailsBlock";
import { GalleryGridBlock, galleryGridDefaultProps } from "./blocks/GalleryGridBlock";
import type { GalleryGridProps } from "./blocks/GalleryGridBlock";
import { GalleryMasonryBlock, galleryMasonryDefaultProps } from "./blocks/GalleryMasonryBlock";
import type { GalleryMasonryProps } from "./blocks/GalleryMasonryBlock";
import { CollectionCardBlock, collectionCardDefaultProps, COLLECTION_CARD_RATIOS, type CollectionCardProps, type CollectionCardRatio } from "./blocks/CollectionCardBlock";
import { FeaturedWorkBlock, featuredWorkDefaultProps, type FeaturedWorkProps } from "./blocks/FeaturedWorkBlock";
const contactDetailsDefaultProps: ContactDetailsProps = {};
// Isomorphic blocks — safe to import the real component + defaults into the client.
import {
  VideoBlock,
  videoDefaultProps,
  type VideoBlockProps,
} from "./blocks/VideoBlock";
import { EditorContainerAnchor } from "./blocks/EditorContainerAnchor";
import { masonryCloneBlockConfig, type MasonryCloneProps } from "./blocks/MasonryCloneBlock";
import {
  HeadingBlock,
  TextBlock,
  ImageBlock,
  ButtonBlock,
  SpacerBlock,
  DividerBlock,
  ColumnsBlock,
  ContainerBlock,
  headingDefaultProps,
  textDefaultProps,
  imageDefaultProps,
  buttonDefaultProps,
  spacerDefaultProps,
  dividerDefaultProps,
  columnsDefaultProps,
  containerDefaultProps,
  containerAnchorDefaultProps,
  type HeadingBlockProps,
  type TextBlockProps,
  type ImageBlockProps,
  type ButtonBlockProps,
  type SpacerBlockProps,
  type DividerBlockProps,
  type ColumnsBlockProps,
  type ContainerBlockProps,
  type ContainerHeight,
  type ContainerAlignX,
  type ContainerAlignY,
  type ContainerAnchorProps,
} from "./blocks/manualBlocks";

type NavPresetKey = (typeof NAV_PRESET_KEYS)[number];

// The `nav` group's 3 preset keys render through NavigationBlock, not
// ContainerBlock — they're carved out of the otherwise-uniform preset Record.
type EditorComponents = Omit<Record<SectionPresetKey, ContainerBlockProps>, NavPresetKey> &
  Record<NavPresetKey, NavigationBlockProps> & {
    // Data blocks
    GalleryGrid: GalleryGridProps;
    GalleryMasonry: GalleryMasonryProps;
    FeaturedWork: FeaturedWorkProps;
    CollectionCard: CollectionCardProps;
    Video: VideoBlockProps;
    ContactDetails: ContactDetailsProps;
    // Manual primitives
    Heading: HeadingBlockProps;
    Text: TextBlockProps;
    Image: ImageBlockProps;
    Button: ButtonBlockProps;
    Spacer: SpacerBlockProps;
    Divider: DividerBlockProps;
    Columns: ColumnsBlockProps;
    Container: ContainerBlockProps;
    ContainerAnchor: ContainerAnchorProps;
    MasonryClone: MasonryCloneProps;
    Navigation: NavigationBlockProps;
  };

// ---------------------------------------------------------------------------
// Shared preview chrome (uses the brand-kit CSS vars applied by the editor
// wrapper, so previews echo the portfolio's colors/fonts).
// ---------------------------------------------------------------------------

function Preview({
  label,
  lines,
  blockStyle,
  puck,
}: {
  label: string;
  lines: Array<string | null | undefined>;
  blockStyle?: BlockStyle;
  puck?: { dragRef?: ((element: Element | null) => void) | null };
}) {
  const shown = lines.filter((l): l is string => Boolean(l && l.trim()));
  return (
    <section
      ref={puck?.dragRef ?? undefined}
      style={{
        border: "1px solid color-mix(in srgb, var(--pf-color-fg) 15%, transparent)",
        background: "var(--pf-color-bg)",
        color: "var(--pf-color-fg)",
        fontFamily: "var(--pf-font-body)",
        padding: "1.5rem",
        margin: 0,
        ...resolveBlockStyle(blockStyle),
      }}
    >
      <span
        style={{
          display: "inline-block",
          fontSize: "0.6875rem",
          textTransform: "uppercase",
          letterSpacing: "0.05em",
          opacity: 0.55,
          marginBottom: "0.5rem",
        }}
      >
        {label}
      </span>
      {shown.map((line, i) => (
        <p
          key={i}
          style={{
            margin: "0.15rem 0",
            fontFamily: i === 0 ? "var(--pf-font-heading)" : "var(--pf-font-body)",
            fontSize: i === 0 ? "1.125rem" : "0.875rem",
            opacity: i === 0 ? 1 : 0.7,
            whiteSpace: "pre-line",
          }}
        >
          {line}
        </p>
      ))}
    </section>
  );
}

// ---------------------------------------------------------------------------
// Shared field helpers (pure functions — labels are passed as arguments)
// ---------------------------------------------------------------------------

// Plain text/textarea field. (Text styling is section-wide via the `_style`
// toolkit — there is no per-text toolbar.) Kept as a helper so block configs
// read uniformly; `multiline` picks textarea. `contentEditable` enables Puck's
// on-canvas inline editing alongside the Content-tab input (the field stays
// hidden from the sidebar via `visible:false`/resolveFields — inline editing is
// independent of sidebar visibility).
function richTextField(label: string, multiline = false): Field<string> {
  return { type: multiline ? "textarea" : "text", label, contentEditable: true } as Field<string>;
}

/** Multi-image Puck custom field backed by the unified MediaPicker. Wired to the
 *  gallery blocks in sub-project #2; defined here with tests as its deliverable. */
// eslint-disable-next-line @typescript-eslint/no-unused-vars
function imagesField(label: string, opts: { max?: number } = {}): Field<MediaPickerSelection[]> {
  return {
    type: "custom",
    label,
    render: ({ value, onChange }: { value: unknown; onChange: (v: unknown) => void }) => (
      <MultiImageControl
        value={(value as MediaPickerSelection[]) ?? []}
        onChange={onChange as (v: MediaPickerSelection[]) => void}
        max={opts.max}
      />
    ),
  } as unknown as Field<MediaPickerSelection[]>;
}

// ---------------------------------------------------------------------------
// Pure field-visibility resolver — hides sidebar fields managed by
// StyleToolkitField panels so only `_style` + `content` ever appear.
// ---------------------------------------------------------------------------

// Hides sidebar fields that are managed by the StyleToolkitField Content/Layout tabs.
// The double cast is required because Puck's resolveFields return type is a strict
// branded Fields<T> — we need to go through unknown to avoid the structural mismatch.
function resolveContainerFields(_data: unknown, { fields }: { fields: Record<string, unknown> }) {
  const { bgAnimation: _ba, bgSpeed: _bs, overlayOpacity: _o, overlayColorToken: _oc, alignX: _ax, alignY: _ay, minHeight: _mh, ...rest } = fields;
  return rest;
}
const resolveContainerFieldsTyped = resolveContainerFields as unknown as ComponentConfig<ContainerBlockProps>["resolveFields"];

// ---------------------------------------------------------------------------
// Anchor presence: resolveData gives an empty Container one editor-only anchor.
// Once the slot has real children, it removes every anchor so the canvas and
// public renderer distribute exactly the same flex children. Puck calls this
// resolver on insert/load/replace/force; the slot's native minEmptyHeight keeps
// a container droppable after its final real child is deleted.
// IDEMPOTENCY: an empty container with the correctly formed anchor retains its
// data reference, avoiding a spurious resolve → change → resolve loop.
// ---------------------------------------------------------------------------

type _SlotItem = { type: string; props: Record<string, unknown> };

function resolveContainerData(data: unknown) {
  const d = data as {
    props: { id: string; content: _SlotItem[] };
  };
  const content: _SlotItem[] = d.props.content ?? [];

  const isAnchor = (item: _SlotItem) => item.type === "ContainerAnchor";
  const realChildren = content.filter((item) => !isAnchor(item));

  // The anchor is empty-state editor plumbing only. Once actual content exists,
  // remove it before Puck lays out the flex slot: the public renderer omits
  // anchors, so keeping one here makes canvas distribution disagree with preview.
  if (realChildren.length > 0) {
    if (content.length === realChildren.length) return data;
    return {
      ...d,
      props: { ...d.props, content: realChildren },
    };
  }

  // Idempotency: if a correctly-formed anchor already leads the slot, nothing to do.
  // The id check is required: drafts saved before the --anchor convention was
  // introduced may carry an anchor whose id matches the container id (no suffix).
  // Passing those through unchanged causes a selection-bounce useEffect loop
  // (parentId === id → selectedItem never escapes the guard → infinite setState).
  const first = content[0];
  if (
    first !== undefined &&
    isAnchor(first) &&
    content.length === 1 &&
    (first.props as { id?: string }).id === `${d.props.id}--anchor`
  ) {
    return data;
  }

  // Height is intentionally 0 — EditorContainerAnchor computes it reactively.
  const anchor: _SlotItem = {
    type: "ContainerAnchor",
    props: {
      id: `${d.props.id}--anchor`,
      height: 0,
    },
  };

  return { ...d, props: { ...d.props, content: [anchor] } };
}
const resolveContainerDataTyped =
  resolveContainerData as unknown as ComponentConfig<ContainerBlockProps>["resolveData"];

// ---------------------------------------------------------------------------
// Translation type. The factory accepts the same `t` function returned by
// next-intl's useTranslations("app.pageBuilder.editor"). The English fallback
// is a static map — it keeps editorPuckConfig (used in tests) unchanged.
// ---------------------------------------------------------------------------

export type PuckTranslate = (key: string) => string;

/** English fallback — keyed under app.pageBuilder.editor.puckConfig.* */
const ENGLISH_PUCK_T: Record<string, string> = {
  "puckConfig.categories.presets": "Preset blocks",
  "puckConfig.categories.manual": "Manual blocks",
  "puckConfig.blocks.galleryGrid": "Photo Grid",
  "puckConfig.blocks.galleryMasonry": "Masonry",
  "puckConfig.blocks.featuredWork": "Highlights",
  "puckConfig.blocks.collectionCard": "Collection card",
  "puckConfig.fields.collectionCrop": "Crop",
  "puckConfig.fields.collectionCaption": "Caption",
  "puckConfig.options.collectionCaption.show": "Show",
  "puckConfig.options.collectionCaption.hide": "Hide",
  "puckConfig.blocks.video": "Video",
  "puckConfig.blocks.contactDetails": "Contact Details",
  "puckConfig.blocks.heading": "Heading",
  "puckConfig.blocks.text": "Text",
  "puckConfig.blocks.image": "Image",
  "puckConfig.blocks.button": "Button",
  "puckConfig.blocks.spacer": "Spacer",
  "puckConfig.blocks.divider": "Divider",
  "puckConfig.blocks.columns": "Columns",
  "puckConfig.blocks.container": "Container",
  "puckConfig.blocks.navigation": "Navigation",
  "puckConfig.fields.style": "Style",
  "puckConfig.fields.pageStyle": "Page style",
  "puckConfig.fields.bgAnimation": "Background animation",
  "puckConfig.fields.bgAnimationShort": "BG animation",
  "puckConfig.fields.bgSpeed": "Animation speed",
  "puckConfig.fields.bgSpeedShort": "BG speed",
  "puckConfig.fields.overlayOpacity": "Overlay opacity (0-100)",
  "puckConfig.fields.overlayColor": "Overlay color",
  "puckConfig.options.overlayColor.none": "None (black)",
  "puckConfig.options.overlayColor.primary": "Primary",
  "puckConfig.options.overlayColor.secondary": "Secondary",
  "puckConfig.options.overlayColor.accent": "Accent",
  "puckConfig.options.overlayColor.background": "Background",
  "puckConfig.options.overlayColor.foreground": "Foreground",
  "puckConfig.fields.minHeight": "Min height",
  "puckConfig.fields.alignX": "Horizontal align",
  "puckConfig.fields.alignY": "Vertical align",
  "puckConfig.fields.backgroundImages": "Background images",
  "puckConfig.fields.headingText": "Heading text",
  "puckConfig.fields.headingLevel": "Level",
  "puckConfig.fields.textContent": "Text",
  "puckConfig.fields.videoUrl": "YouTube or Vimeo URL",
  "puckConfig.fields.imageAlt": "Alt text",
  "puckConfig.fields.buttonLabel": "Button label",
  "puckConfig.fields.buttonSize": "Size",
  "puckConfig.fields.buttonAction": "Action",
  "puckConfig.fields.buttonAlign": "Alignment",
  "puckConfig.fields.spacerHeight": "Height",
  "puckConfig.fields.dividerThickness": "Thickness (px)",
  "puckConfig.fields.columnsCount": "Columns",
  "puckConfig.fields.rowsCount": "Rows",
  "puckConfig.options.bgAnimation.crossfade": "Crossfade",
  "puckConfig.options.bgAnimation.kenburns": "Ken Burns",
  "puckConfig.options.bgAnimation.slide": "Slide",
  "puckConfig.options.bgSpeed.slow": "Slow (7s)",
  "puckConfig.options.bgSpeed.medium": "Medium (5s)",
  "puckConfig.options.bgSpeed.fast": "Fast (3s)",
  "puckConfig.options.bgSpeedShort.slow": "Slow",
  "puckConfig.options.bgSpeedShort.medium": "Medium",
  "puckConfig.options.bgSpeedShort.fast": "Fast",
  "puckConfig.options.minHeight.auto": "Auto",
  "puckConfig.options.minHeight.short": "Short (40vh)",
  "puckConfig.options.minHeight.medium": "Medium (60vh)",
  "puckConfig.options.minHeight.tall": "Tall (80vh)",
  "puckConfig.options.minHeightShort.auto": "Auto",
  "puckConfig.options.minHeightShort.short": "Short",
  "puckConfig.options.minHeightShort.medium": "Medium",
  "puckConfig.options.minHeightShort.tall": "Tall",
  "puckConfig.options.alignX.left": "Left",
  "puckConfig.options.alignX.center": "Center",
  "puckConfig.options.alignX.right": "Right",
  "puckConfig.options.alignY.top": "Top",
  "puckConfig.options.alignY.center": "Center",
  "puckConfig.options.alignY.bottom": "Bottom",
  "puckConfig.options.headingLevel.h1": "Display",
  "puckConfig.options.headingLevel.h2": "Title",
  "puckConfig.options.headingLevel.h3": "Heading",
  "puckConfig.options.headingLevel.h4": "Subheading",
  "puckConfig.options.headingLevel.h5": "Caption",
  "puckConfig.options.headingLevel.h6": "Label",
  "puckConfig.options.buttonSize.sm": "Small",
  "puckConfig.options.buttonSize.md": "Medium",
  "puckConfig.options.buttonSize.lg": "Large",
  "puckConfig.options.buttonAction.openContact": "Open contact form",
  "puckConfig.options.buttonAction.goToGallery": "Go to Gallery page",
  "puckConfig.options.buttonAction.goToHome": "Go to Home page",
  "puckConfig.options.buttonAlign.left": "Left",
  "puckConfig.options.buttonAlign.center": "Center",
  "puckConfig.options.buttonAlign.right": "Right",
};

// 11 group labels + 33 x (label + description) — derived off the registry so
// this fallback map can't drift from SECTION_PRESETS instead of hand-typing
// 77 more lines.
for (const group of PRESET_GROUPS) {
  ENGLISH_PUCK_T[group.labelKey] = group.label;
}
for (const presetKey of SECTION_PRESET_KEYS) {
  const presetEntry = SECTION_PRESETS[presetKey];
  ENGLISH_PUCK_T[presetEntry.labelKey] = presetEntry.label;
  ENGLISH_PUCK_T[presetEntry.descriptionKey] = presetEntry.description;
}

// Exported so the parity test can wrap it to record misses (a key that falls
// through to `?? key` renders literally, e.g. "puckConfig.blocks.heroSplitPreset").
export function englishPuckT(key: string): string {
  return ENGLISH_PUCK_T[key] ?? key;
}

// ---------------------------------------------------------------------------
// Navigation's `_style` field — same "custom" field mechanism as `styleField`
// below, plus the detach-toggle context StyleToolkitField's NavigationConfigPanel
// needs (see chromeSyncContext.ts). A real component (not a plain closure) so
// `useChromeSync()` runs as an ordinary hook call.
// ---------------------------------------------------------------------------

export function NavStyleField({
  value,
  onChange,
  id,
  t,
  zone,
}: {
  value: unknown;
  onChange: (v: unknown) => void;
  id: string;
  t: PuckTranslate;
  zone?: ZoneKey;
}) {
  const chromeSync = useChromeSync();
  const otherZone: ZoneKey | undefined = zone === "home" ? "gallery" : zone === "gallery" ? "home" : undefined;
  // `zone` is undefined until the caller (EditorShell) passes `activeZone` into
  // `createEditorConfig` — see this file's handoff note. Until then the toggle
  // renders with StyleToolkitField's own generic fallback copy, always enabled.
  const navDetach: NavDetachContext | undefined =
    zone && otherZone && chromeSync
      ? {
          zoneLabel: t(`zone.${zone}`),
          otherZoneLabel: t(`zone.${otherZone}`),
          disabled: !chromeSync.canDetach(zone, "nav"),
        }
      : undefined;

  return (
    <StyleToolkitField
      value={value as BlockStyle | undefined}
      onChange={onChange as (v: BlockStyle) => void}
      fieldId={id}
      navDetach={navDetach}
    />
  );
}

// ---------------------------------------------------------------------------
// Factory — builds the editor Puck config with translated labels.
// Called inside EditorShell via useMemo(() => createEditorConfig(t), [t])
// where t = useTranslations("app.pageBuilder.editor").
// ---------------------------------------------------------------------------

export function createEditorConfig(
  t: PuckTranslate,
  // Seam for the detach-toggle's zone context — see NavStyleField/chromeSyncContext.ts.
  // Undefined today (no call site passes it yet); the toggle degrades to
  // StyleToolkitField's generic always-enabled fallback until a caller supplies it.
  activeZone?: ZoneKey
): Config<EditorComponents> {
  // ---- Shared fields -------------------------------------------------------

  const styleField = {
    type: "custom",
    label: t("puckConfig.fields.style"),
    render: ({ value, onChange, id }: { value: unknown; onChange: (v: unknown) => void; id: string }) => (
      <StyleToolkitField
        value={value as BlockStyle | undefined}
        onChange={onChange as (v: BlockStyle) => void}
        fieldId={id}
      />
    ),
  } as unknown as Field<BlockStyle | undefined>;

  const rootStyleField = {
    type: "custom",
    label: t("puckConfig.fields.pageStyle"),
    render: ({ value, onChange }: { value: unknown; onChange: (v: unknown) => void }) => (
      <RootStyleField
        value={value as RootPageStyle | undefined}
        onChange={onChange as (v: RootPageStyle) => void}
      />
    ),
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  } as unknown as Field<any>;

  // ---- Navigation fields (editor-only `_style` override) ------------------
  // Mirrors `editorContainerFields` below: `navigationFields`'s own `_style` is
  // the inert `productionStyleField` (round-trip-only, keeps StyleToolkitField
  // out of the server-rendered production config.ts bundle) — this swaps it
  // for the real editor field so the Navigation config panel actually renders.

  const navStyleField = {
    type: "custom",
    label: t("puckConfig.fields.style"),
    render: ({ value, onChange, id }: { value: unknown; onChange: (v: unknown) => void; id: string }) => (
      <NavStyleField value={value} onChange={onChange} id={id} t={t} zone={activeZone} />
    ),
  } as unknown as Field<BlockStyle | undefined>;

  const navigationEditorFields = {
    ...navigationFields,
    _style: navStyleField,
  } as unknown as ComponentConfig<NavigationBlockProps>["fields"];

  // ---- Container fields (used by Container + all preset blocks) -----------

  const editorContainerFields = {
    _style: styleField,
    bgAnimation: {
      type: "select",
      label: t("puckConfig.fields.bgAnimation"),
      visible: false,
      options: [
        { label: t("puckConfig.options.bgAnimation.crossfade"), value: "crossfade" },
        { label: t("puckConfig.options.bgAnimation.kenburns"), value: "kenburns" },
        { label: t("puckConfig.options.bgAnimation.slide"), value: "slide" },
      ],
    } as unknown as Field<ContainerBlockProps["bgAnimation"]>,
    bgSpeed: {
      type: "select",
      label: t("puckConfig.fields.bgSpeed"),
      visible: false,
      options: [
        { label: t("puckConfig.options.bgSpeed.slow"), value: "slow" },
        { label: t("puckConfig.options.bgSpeed.medium"), value: "medium" },
        { label: t("puckConfig.options.bgSpeed.fast"), value: "fast" },
      ],
    } as unknown as Field<ContainerBlockProps["bgSpeed"]>,
    overlayOpacity: { type: "number", label: t("puckConfig.fields.overlayOpacity"), min: 0, max: 100, visible: false } as unknown as Field<number | undefined>,
    overlayColorToken: {
      type: "select",
      label: t("puckConfig.fields.overlayColor"),
      visible: false,
      options: [
        { label: t("puckConfig.options.overlayColor.none"), value: "" },
        { label: t("puckConfig.options.overlayColor.primary"), value: "primary" },
        { label: t("puckConfig.options.overlayColor.secondary"), value: "secondary" },
        { label: t("puckConfig.options.overlayColor.accent"), value: "accent" },
        { label: t("puckConfig.options.overlayColor.background"), value: "background" },
        { label: t("puckConfig.options.overlayColor.foreground"), value: "foreground" },
      ],
    } as unknown as Field<StyleColorToken | undefined>,
    minHeight: {
      type: "select",
      label: t("puckConfig.fields.minHeight"),
      options: [
        { label: t("puckConfig.options.minHeight.auto"), value: "auto" },
        { label: t("puckConfig.options.minHeight.short"), value: "short" },
        { label: t("puckConfig.options.minHeight.medium"), value: "medium" },
        { label: t("puckConfig.options.minHeight.tall"), value: "tall" },
      ],
    } as unknown as Field<ContainerHeight | undefined>,
    alignX: {
      type: "select",
      label: t("puckConfig.fields.alignX"),
      visible: false,
      options: [
        { label: t("puckConfig.options.alignX.left"), value: "left" },
        { label: t("puckConfig.options.alignX.center"), value: "center" },
        { label: t("puckConfig.options.alignX.right"), value: "right" },
      ],
    } as unknown as Field<ContainerAlignX | undefined>,
    alignY: {
      type: "select",
      label: t("puckConfig.fields.alignY"),
      visible: false,
      options: [
        { label: t("puckConfig.options.alignY.top"), value: "top" },
        { label: t("puckConfig.options.alignY.center"), value: "center" },
        { label: t("puckConfig.options.alignY.bottom"), value: "bottom" },
      ],
    } as unknown as Field<ContainerAlignY | undefined>,
    content: { type: "slot" },
  } as unknown as ComponentConfig<ContainerBlockProps>["fields"];

  // ---- Preset block editor configs (derived from SECTION_PRESETS) ---------
  // 36 keys, one ComponentConfig each — same shape the ten hand-written consts
  // used to have. metadata (e.g. GalleryLandingPreset's backgroundImagesHint)
  // comes straight off the registry entry so it is never duplicated here.
  // The `nav` group's 3 keys render through NavigationBlock instead of
  // ContainerBlock (componentType: "Navigation" on the registry entry).

  const presetComponents = Object.fromEntries(
    SECTION_PRESET_KEYS.map((key) => {
      const presetEntry = SECTION_PRESETS[key];
      if (presetEntry.componentType === "Navigation") {
        const navCfg: ComponentConfig<NavigationBlockProps> = {
          label: t(presetEntry.labelKey),
          inline: true,
          fields: navigationEditorFields,
          defaultProps: presetEntry.defaultProps as NavigationBlockProps,
          permissions: navigationPermissions,
          render: NavigationBlock,
        };
        return [key, navCfg] as const;
      }
      const cfg: ComponentConfig<ContainerBlockProps> = {
        label: t(presetEntry.labelKey),
        // inline so the section root (which carries colSpan/rowSpan grid placement) is
        // the grid child in the editor canvas, matching the public render. Without it
        // Puck wraps the block and the span lands on the inner section (ignored).
        inline: true,
        fields: editorContainerFields,
        resolveFields: resolveContainerFieldsTyped,
        defaultProps: presetEntry.defaultProps as ContainerBlockProps,
        render: ContainerBlock,
        ...(presetEntry.metadata ? { metadata: presetEntry.metadata } : {}),
      };
      return [key, cfg] as const;
    })
  ) as unknown as Omit<Record<SectionPresetKey, ComponentConfig<ContainerBlockProps>>, NavPresetKey> &
    Record<NavPresetKey, ComponentConfig<NavigationBlockProps>>;

  // ---- Gallery data blocks -------------------------------------------------

  const galleryGrid: ComponentConfig<GalleryGridProps> = {
    label: t("puckConfig.blocks.galleryGrid"),
    inline: true,
    defaultProps: galleryGridDefaultProps,
    // `images` is intentionally absent — the editor drives it via StyleToolkitField.
    // columns/gap moved to _style.galleryColumns/_style.galleryGap (Layout tab Gallery section).
    // No background-image controls: the grid's own content IS its images now
    // (see bannerLayers.ts). `minHeight` is hidden and managed by StyleToolkitField;
    // resolveFields strips it so it never appears in the standard Puck sidebar.
    fields: {
      _style: styleField,
      content: { type: "slot", allow: ["Image"] },
      minHeight: { type: "select", label: t("puckConfig.fields.minHeight"), visible: false, options: [{ label: t("puckConfig.options.minHeightShort.auto"), value: "auto" }, { label: t("puckConfig.options.minHeightShort.short"), value: "short" }, { label: t("puckConfig.options.minHeightShort.medium"), value: "medium" }, { label: t("puckConfig.options.minHeightShort.tall"), value: "tall" }] } as unknown as Field<ContainerHeight | undefined>,
    } as unknown as Fields<GalleryGridProps>,
    resolveFields: (_data, { fields }) => {
      const { minHeight: _mh, ...rest } = fields as Record<string, unknown>;
      return rest as typeof fields;
    },
    render: GalleryGridBlock,
  };

  const galleryMasonry: ComponentConfig<GalleryMasonryProps> = {
    label: t("puckConfig.blocks.galleryMasonry"),
    inline: true,
    defaultProps: galleryMasonryDefaultProps,
    // `images` is intentionally absent — driven by StyleToolkitField.
    // columns/gap moved to _style.galleryColumns/_style.galleryGap (Layout tab Gallery section).
    // No background-image controls: the masonry's own content IS its images now
    // (see bannerLayers.ts).
    fields: {
      _style: styleField,
      content: { type: "slot", allow: ["Image"] },
      column1: { type: "slot", allow: ["Image", "MasonryClone"] },
      column2: { type: "slot", allow: ["Image", "MasonryClone"] },
      column3: { type: "slot", allow: ["Image", "MasonryClone"] },
      column4: { type: "slot", allow: ["Image", "MasonryClone"] },
      minHeight: { type: "select", label: t("puckConfig.fields.minHeight"), visible: false, options: [{ label: t("puckConfig.options.minHeightShort.auto"), value: "auto" }, { label: t("puckConfig.options.minHeightShort.short"), value: "short" }, { label: t("puckConfig.options.minHeightShort.medium"), value: "medium" }, { label: t("puckConfig.options.minHeightShort.tall"), value: "tall" }] } as unknown as Field<ContainerHeight | undefined>,
    } as unknown as Fields<GalleryMasonryProps>,
    resolveFields: (_data, { fields }) => {
      const { minHeight: _mh, ...rest } = fields as Record<string, unknown>;
      return rest as typeof fields;
    },
    render: GalleryMasonryBlock,
  };

  const featuredWork: ComponentConfig<FeaturedWorkProps> = {
    label: t("puckConfig.blocks.featuredWork"),
    inline: true,
    defaultProps: featuredWorkDefaultProps,
    permissions: { insert: false },
    // `collections` is intentionally absent — driven by StyleToolkitField Content tab.
    // columns moved to _style.galleryColumns (Layout tab Gallery section).
    // Banner fields are hidden (visible: false) and managed by StyleToolkitField.
    fields: {
      _style: styleField,
      backgroundImages: { type: "array", label: t("puckConfig.fields.backgroundImages"), visible: false, arrayFields: { id: { type: "text", label: "ID" }, publicId: { type: "text", label: "Public ID" } } } as unknown as Field<FeaturedWorkProps["backgroundImages"]>,
      bgAnimation: { type: "select", label: t("puckConfig.fields.bgAnimationShort"), visible: false, options: [{ label: t("puckConfig.options.bgAnimation.crossfade"), value: "crossfade" }, { label: t("puckConfig.options.bgAnimation.kenburns"), value: "kenburns" }, { label: t("puckConfig.options.bgAnimation.slide"), value: "slide" }] } as unknown as Field<FeaturedWorkProps["bgAnimation"]>,
      bgSpeed: { type: "select", label: t("puckConfig.fields.bgSpeedShort"), visible: false, options: [{ label: t("puckConfig.options.bgSpeedShort.slow"), value: "slow" }, { label: t("puckConfig.options.bgSpeedShort.medium"), value: "medium" }, { label: t("puckConfig.options.bgSpeedShort.fast"), value: "fast" }] } as unknown as Field<FeaturedWorkProps["bgSpeed"]>,
      overlayOpacity: { type: "number", label: t("puckConfig.fields.overlayOpacity"), visible: false, min: 0, max: 100 } as unknown as Field<number | undefined>,
      minHeight: { type: "select", label: t("puckConfig.fields.minHeight"), visible: false, options: [{ label: t("puckConfig.options.minHeightShort.auto"), value: "auto" }, { label: t("puckConfig.options.minHeightShort.short"), value: "short" }, { label: t("puckConfig.options.minHeightShort.medium"), value: "medium" }, { label: t("puckConfig.options.minHeightShort.tall"), value: "tall" }] } as unknown as Field<ContainerHeight | undefined>,
    } as unknown as Fields<FeaturedWorkProps>,
    resolveFields: (_data, { fields }) => {
      const { backgroundImages: _bi, bgAnimation: _ba, bgSpeed: _bs, overlayOpacity: _o, minHeight: _mh, ...rest } = fields as Record<string, unknown>;
      return rest as typeof fields;
    },
    render: FeaturedWorkBlock,
  };

  // ---- Collection card ------------------------------------------------------

  const collectionCard: ComponentConfig<CollectionCardProps> = {
    label: t("puckConfig.blocks.collectionCard"),
    inline: true,
    defaultProps: collectionCardDefaultProps,
    // `collection` is intentionally absent — driven by StyleToolkitField Content
    // tab's collection picker, exactly like FeaturedWork's `collections`.
    fields: {
      _style: styleField,
      // The custom Content tab owns every content setting so Puck's native
      // fields cannot leak Crop/Caption beneath Design or Layout.
      aspectRatio: { type: "select", label: t("puckConfig.fields.collectionCrop"), visible: false, options: COLLECTION_CARD_RATIOS.map((r) => ({ label: r.replace(/ /g, ""), value: r })) } as unknown as Field<CollectionCardRatio | undefined>,
      showCaption: { type: "radio", label: t("puckConfig.fields.collectionCaption"), visible: false, options: [{ label: t("puckConfig.options.collectionCaption.show"), value: true }, { label: t("puckConfig.options.collectionCaption.hide",), value: false }] } as unknown as Field<boolean | undefined>,
    } as unknown as Fields<CollectionCardProps>,
    resolveFields: (_data, { fields }) => {
      const { aspectRatio: _ar, showCaption: _sc, ...rest } = fields as Record<string, unknown>;
      return rest as typeof fields;
    },
    render: CollectionCardBlock,
  };

  // ---- Video ---------------------------------------------------------------

  const video: ComponentConfig<VideoBlockProps> = {
    label: t("puckConfig.blocks.video"),
    inline: true,
    defaultProps: videoDefaultProps,
    fields: {
      _style: styleField,
      videoUrl: { type: "text", label: t("puckConfig.fields.videoUrl"), visible: false } as unknown as Field<string>,
    },
    resolveFields: (_data, { fields }) => {
      // videoUrl is managed by the Content tab in StyleToolkitField.
      const { videoUrl: _v, ...rest } = fields as Record<string, unknown>;
      return rest as typeof fields;
    },
    render: VideoBlock,
  };

  // ---- ContactDetails (server-only; editor renders a Preview) -------------

  const contactDetails: ComponentConfig<ContactDetailsProps> = {
    label: t("puckConfig.blocks.contactDetails"),
    inline: true,
    defaultProps: contactDetailsDefaultProps,
    fields: {
      _style: styleField,
    },
    resolveFields: (_data, { fields }) => {
      return { _style: (fields as Record<string, unknown>)._style } as typeof fields;
    },
    render: ({ _style, columns, email, phone, address, instagram, facebook, tiktok, website, puck }) => {
      // WYSIWYG canvas: render the actual contact rows using prop values so the canvas
      // reflects what the user typed in the Content tab. When all fields are blank
      // the workspace contact data fills in at runtime; show a placeholder here.
      // No confirmMessage passed → SocialIconLink clicks are no-ops in the editor.

      // Pre-normalize social hrefs so we match production SocialsRow exactly
      // (skips invalid URLs, avoids double-prefixing full https:// values).
      const igHref = instagram ? normalizeSocialUrl("instagram", instagram) : null;
      const fbHref = facebook ? normalizeSocialUrl("facebook", facebook) : null;
      const ttHref = tiktok ? normalizeSocialUrl("tiktok", tiktok) : null;
      const wsHref = website ? normalizeSocialUrl("website", website) : null;
      const hasSocials = !!(igHref || fbHref || ttHref || wsHref);
      const hasAny = email || phone || address || hasSocials;
      const rowStyle = { display: "flex", flexDirection: "column" as const, gap: "0.125rem" };
      const labelStyle = buildContactLabelStyle(_style);
      const valueStyle = buildContactValueStyle(_style);
      const iconColor = buildContactIconColor(_style);
      const iconSize = buildContactIconSize(_style);
      // Same resolver as production SocialsRow: contactIconAlign wins, then
      // valueAlign, then center. Never re-inline this — the canvas silently
      // drifts from the published page when it does.
      const iconJustify = buildContactIconAlign(_style);
      return (
        <dl
          ref={puck?.dragRef ?? undefined}
          data-block="contact-details"
          style={{
            display: "grid",
            gridTemplateColumns: contactGridTemplate(columns),
            gap: "0.875rem",
            margin: 0,
            padding: "0.5rem 0",
            fontFamily: "var(--pf-font-body)",
            color: "var(--pf-color-fg)",
            ...resolveBlockStyle(_style),
          }}
          {...resolveBlockAttrs(_style)}
        >
          {email && (
            <div style={rowStyle}>
              <dt style={labelStyle}>Email</dt>
              <dd style={{ ...valueStyle, textDecoration: "none" }}>{email}</dd>
            </div>
          )}
          {phone && (
            <div style={rowStyle}>
              <dt style={labelStyle}>Phone</dt>
              <dd style={{ ...valueStyle, textDecoration: "none" }}>{phone}</dd>
            </div>
          )}
          {address && (
            <div style={rowStyle}>
              <dt style={labelStyle}>Address</dt>
              <dd style={valueStyle}>{address}</dd>
            </div>
          )}
          {hasSocials && (
            <div style={{ ...rowStyle, gap: "0.25rem" }}>
              <dt style={labelStyle}>Follow</dt>
              <dd style={{ margin: 0, display: "flex", flexWrap: "wrap", gap: "0.875rem", color: iconColor, justifyContent: iconJustify }}>
                {igHref && <SocialIconLink href={igHref} platform="instagram" size={iconSize} label="Instagram" />}
                {fbHref && <SocialIconLink href={fbHref} platform="facebook" size={iconSize} label="Facebook" />}
                {ttHref && <SocialIconLink href={ttHref} platform="tiktok" size={iconSize} label="TikTok" />}
                {wsHref && <SocialIconLink href={wsHref} platform="website" size={iconSize} label="Website" />}
              </dd>
            </div>
          )}
          {!hasAny && (
            <p style={{ margin: 0, fontSize: "0.875rem", opacity: 0.5, fontFamily: "var(--pf-font-body)" }}>
              Workspace contact details
            </p>
          )}
        </dl>
      );
    },
  };

  // ---- Manual primitives ---------------------------------------------------

  const heading: ComponentConfig<HeadingBlockProps> = {
    label: t("puckConfig.blocks.heading"),
    inline: true,
    defaultProps: headingDefaultProps,
    fields: {
      _style: styleField,
      text: { ...richTextField(t("puckConfig.fields.headingText")), visible: false } as unknown as Field<string>,
      level: {
        type: "select",
        label: t("puckConfig.fields.headingLevel"),
        options: [
          { label: t("puckConfig.options.headingLevel.h1"), value: "h1" },
          { label: t("puckConfig.options.headingLevel.h2"), value: "h2" },
          { label: t("puckConfig.options.headingLevel.h3"), value: "h3" },
          { label: t("puckConfig.options.headingLevel.h4"), value: "h4" },
          { label: t("puckConfig.options.headingLevel.h5"), value: "h5" },
          { label: t("puckConfig.options.headingLevel.h6"), value: "h6" },
        ],
      },
    },
    resolveFields: (_data, { fields }) => {
      // text and level are managed by the Content tab in StyleToolkitField
      const { text: _t, level: _l, ...rest } = fields as Record<string, unknown>;
      return rest as typeof fields;
    },
    render: HeadingBlock,
  };

  const text: ComponentConfig<TextBlockProps> = {
    label: t("puckConfig.blocks.text"),
    inline: true,
    defaultProps: textDefaultProps,
    fields: {
      _style: styleField,
      text: { ...richTextField(t("puckConfig.fields.textContent"), true), visible: false } as unknown as Field<string>,
    },
    resolveFields: (_data, { fields }) => {
      // text is managed by the Content tab in StyleToolkitField
      const { text: _t, ...rest } = fields as Record<string, unknown>;
      return rest as typeof fields;
    },
    render: TextBlock,
  };

  const image: ComponentConfig<ImageBlockProps> = {
    label: t("puckConfig.blocks.image"),
    inline: true,
    defaultProps: imageDefaultProps,
    fields: {
      _style: styleField,
      alt: { type: "text", label: t("puckConfig.fields.imageAlt") },
    },
    resolveFields: (_data, { fields }) => {
      // alt is managed by the Content tab; the background image lives in _style
      // (bgImagePublicId, via the Banner picker) and resize/colSpan/rowSpan in
      // the Layout tab — see StyleToolkitField.tsx.
      const { alt: _a, ...rest } = fields as Record<string, unknown>;
      return rest as typeof fields;
    },
    render: ImageBlock,
  };

  const button: ComponentConfig<ButtonBlockProps> = {
    label: t("puckConfig.blocks.button"),
    inline: true,
    defaultProps: { ...buttonDefaultProps, size: "md" },
    fields: {
      _style: styleField,
      label: { type: "text", label: t("puckConfig.fields.buttonLabel"), contentEditable: true },
      size: {
        type: "select",
        label: t("puckConfig.fields.buttonSize"),
        options: [
          { label: t("puckConfig.options.buttonSize.sm"), value: "sm" },
          { label: t("puckConfig.options.buttonSize.md"), value: "md" },
          { label: t("puckConfig.options.buttonSize.lg"), value: "lg" },
        ],
      },
      action: {
        type: "select",
        label: t("puckConfig.fields.buttonAction"),
        options: [
          { label: t("puckConfig.options.buttonAction.openContact"), value: "open-contact" },
          { label: t("puckConfig.options.buttonAction.goToGallery"), value: "go-to-gallery" },
          { label: t("puckConfig.options.buttonAction.goToHome"), value: "go-to-home" },
        ],
      },
      align: {
        type: "select",
        label: t("puckConfig.fields.buttonAlign"),
        options: [
          { label: t("puckConfig.options.buttonAlign.left"), value: "left" },
          { label: t("puckConfig.options.buttonAlign.center"), value: "center" },
          { label: t("puckConfig.options.buttonAlign.right"), value: "right" },
        ],
      },
    },
    resolveFields: (_data, { fields }) => {
      // label, action, align, and size are managed by StyleToolkitField's Content/Layout tabs
      const { label: _l, action: _a, align: _al, size: _s, ...rest } = fields as Record<string, unknown>;
      return rest as typeof fields;
    },
    render: ButtonBlock,
  };

  const spacer: ComponentConfig<SpacerBlockProps> = {
    label: t("puckConfig.blocks.spacer"),
    inline: true,
    defaultProps: spacerDefaultProps,
    fields: {
      height: {
        type: "custom",
        label: t("puckConfig.fields.spacerHeight"),
        render: ({ value, onChange }: { value: unknown; onChange: (v: unknown) => void }) => (
          <NumberInputRow
            label={t("puckConfig.fields.spacerHeight")}
            value={value as number | undefined}
            min={4}
            max={400}
            suffix="px"
            onChange={onChange as (v: number | undefined) => void}
          />
        ),
      } as unknown as Field<number>,
    },
    render: SpacerBlock,
  };

  const divider: ComponentConfig<DividerBlockProps> = {
    label: t("puckConfig.blocks.divider"),
    inline: true,
    defaultProps: dividerDefaultProps,
    fields: {
      _style: styleField,
      thickness: { type: "number", label: t("puckConfig.fields.dividerThickness"), min: 1, max: 12, visible: false } as unknown as Field<number>,
    },
    resolveFields: (_data, { fields }) => {
      // thickness is managed by the DividerPanel in StyleToolkitField
      return { _style: (fields as Record<string, unknown>)._style } as typeof fields;
    },
    render: DividerBlock,
  };

  const columns: ComponentConfig<ColumnsBlockProps> = {
    label: t("puckConfig.blocks.columns"),
    inline: true,
    defaultProps: {
      ...columnsDefaultProps,
    },
    fields: {
      _style: styleField,
      columns: {
        type: "number",
        label: t("puckConfig.fields.columnsCount"),
        min: 1,
        max: 6,
      } as Field<number>,
      rows: { type: "number", label: t("puckConfig.fields.rowsCount"), min: 1, max: 6 } as Field<number | undefined>,
      content: { type: "slot" },
    },
    resolveFields: (_data, { fields }) => {
      const { columns: _c, rows: _r, ...rest } = fields as Record<string, unknown>;
      void _c; void _r;
      return rest as typeof fields;
    },
    render: ColumnsBlock,
  };

  const container: ComponentConfig<ContainerBlockProps> = {
    label: t("puckConfig.blocks.container"),
    inline: true,
    defaultProps: {
      ...containerDefaultProps,
    },
    fields: editorContainerFields,
    resolveFields: resolveContainerFieldsTyped,
    resolveData: resolveContainerDataTyped,
    render: ContainerBlock,
  };

  // ---- Navigation (base type; not drawer-listed — see the 3 `nav` presets
  // above for the drawer-insertable variants) --------------------------------

  const navigation: ComponentConfig<NavigationBlockProps> = {
    label: t("puckConfig.blocks.navigation"),
    inline: true,
    defaultProps: navigationDefaultProps,
    fields: navigationEditorFields,
    permissions: navigationPermissions,
    render: NavigationBlock,
  };

  // ---- Final config --------------------------------------------------------

  // 12 collapsible drawer categories, one per group. Only the first (nav)
  // starts expanded — 36 items all open at once is an unusable drawer.
  // `defaultExpanded` must be set EXPLICITLY on every group: Puck renders a
  // category that omits the key as expanded, so leaving it off the other
  // eleven opens all of them (observed in the browser before this was pinned).
  const presetCategories = PRESET_GROUPS.reduce<
    Record<string, { title: string; components: SectionPresetKey[]; defaultExpanded: boolean }>
  >((acc, group, i) => {
    acc[group.id] = {
      title: t(group.labelKey),
      components: [...group.keys],
      defaultExpanded: i === 0,
    };
    return acc;
  }, {});

  return {
    categories: {
      ...presetCategories,
      manual: { title: t("puckConfig.categories.manual"), components: [...MANUAL_BLOCK_KEYS], defaultExpanded: false },
    } as Config<EditorComponents>["categories"],
    components: {
      ...presetComponents,
      GalleryGrid: galleryGrid,
      GalleryMasonry: galleryMasonry,
      FeaturedWork: featuredWork,
      CollectionCard: collectionCard,
      Video: video,
      ContactDetails: contactDetails,
      Heading: heading,
      Text: text,
      Image: image,
      Button: button,
      Spacer: spacer,
      Divider: divider,
      Columns: columns,
      Container: container,
      Navigation: navigation,
      ContainerAnchor: {
        label: "ContainerAnchor",
        defaultProps: containerAnchorDefaultProps,
        fields: {
          height: { type: "number", label: t("puckConfig.fields.spacerHeight") } as unknown as Field<number>,
        },
        permissions: {
          drag: false,
          delete: false,
          duplicate: false,
          insert: false,
          edit: false,
        },
        // Thin wrapper: delegates to EditorContainerAnchor which self-sizes via
        // usePuckStore and bounces selection to the parent container. Returns null
        // on the public page (puck.isEditing is false/absent in <Render>).
        render: (({ id, puck }: { id?: string; puck?: { isEditing?: boolean }; [k: string]: unknown }) =>
          puck?.isEditing && id ? <EditorContainerAnchor id={id} /> : null
        ) as unknown as ComponentConfig<ContainerAnchorProps>["render"],
      } as ComponentConfig<ContainerAnchorProps>,
      MasonryClone: masonryCloneBlockConfig,
    },
    // No root.render in the editor: Puck wraps blocks in a DropZone div, so
    // blocks are not direct children of any wrapper here — adding root.render
    // breaks DnD position tracking without giving us align-self preview either.
    // The flex-col root lives only in config.ts (production <Render>), where
    // blocks ARE direct children and align-self works correctly.
    root: { fields: { _rootStyle: rootStyleField } },
  };
}

/** English-label config for backward compat (tests) and as the initial seed
 *  before EditorShell's useMemo produces the locale-aware version. */
export const editorPuckConfig: Config<EditorComponents> = createEditorConfig(englishPuckT);
