"use server";

import { Workspace, PromoCode, User } from "@/lib/db/models";
import { ownerContext } from "@/lib/auth/ownerContext";
import { grantPlan } from "@/lib/billing/grantPlan";

export type RedeemPromoCodeResult =
  | { ok: true; startsImmediately: boolean }
  | { error: string };

// Looking up the PromoCode doc is unavoidable here: its _id is generated by
// Mongo at insert time in the test fixture, so the only way to record it on
// Workspace.codesRedeemed is a DB read keyed by the submitted code string.
export async function redeemPromoCodeAction(code: string): Promise<RedeemPromoCodeResult> {
  const ctx = await ownerContext({ allowWhenGated: true });
  if ("error" in ctx) return { error: ctx.error };

  const normalized = code.trim().toLowerCase();
  const promoCode = await PromoCode.findOne({ code: normalized });
  if (!promoCode) return { error: "promo_code_not_found" };
  if (promoCode.expiresAt && promoCode.expiresAt < new Date()) {
    return { error: "promo_code_expired" };
  }

  if (promoCode.type === "beta2mo") {
    const user = await User.findOne({ workosUserId: ctx.userId }).lean();
    if (!user?.betaParticipation?.recordedAt) {
      return { error: "not_eligible_beta_participant" };
    }
  }

  // $addToSet is naturally idempotent (adding the same id twice is a no-op),
  // so gating this write on { codesRedeemed: { $ne } } and checking
  // modifiedCount is both the "already redeemed" check AND the defense
  // against two concurrent redemptions of the same code. Run it BEFORE
  // grantPlan: granting first would let a plain sequential resubmit of an
  // already-used code re-run grantPlan and push planGrantExpiresAt further
  // out every time, even though the function ultimately returns
  // "already redeemed".
  const redeemResult = await Workspace.updateOne(
    { _id: ctx.workspace._id, codesRedeemed: { $ne: promoCode._id } },
    { $addToSet: { codesRedeemed: promoCode._id } }
  );
  if (redeemResult.modifiedCount === 0) {
    return { error: "promo_code_already_redeemed" };
  }

  let expiresAt: Date | null = null;
  if (promoCode.type === "yearly") {
    expiresAt = new Date();
    expiresAt.setFullYear(expiresAt.getFullYear() + 1);
  } else if (promoCode.type === "monthly") {
    expiresAt = new Date();
    expiresAt.setMonth(expiresAt.getMonth() + 1);
  }
  const plan = promoCode.type === "beta" ? "beta" : "pro";
  await grantPlan(ctx.workspace._id, { plan, expiresAt });

  return { ok: true, startsImmediately: true };
}
