"use server";

import mongoose from "mongoose";
import { Workspace, PromoCode, User } from "@/lib/db/models";
import { ownerContext } from "@/lib/auth/ownerContext";
import { grantPlan } from "@/lib/billing/grantPlan";
import { isEntitled } from "@/lib/billing/access";
import { hasActivatedOnboardingPlan } from "@/lib/onboarding/planActivation";

const BETA2MO_GRANT_MONTHS = 2;

export type RedeemPromoCodeResult =
  | { ok: true; startsImmediately: boolean }
  | { error: string };

// Looking up the PromoCode doc is unavoidable here: its _id is generated by
// Mongo at insert time in the test fixture, so the only way to record it on
// Workspace.codesRedeemed is a DB read keyed by the submitted code string.
export async function redeemPromoCodeAction(
  code: string,
  options: { onboarding?: boolean } = {}
): Promise<RedeemPromoCodeResult> {
  // The code drawer is part of the onboarding plan step. Keep the owner and
  // billing safeguards, but let an unfinished onboarding session redeem here.
  const ctx = await ownerContext({ allowDuringOnboarding: true, allowWhenGated: true });
  if ("error" in ctx) return { error: ctx.error };
  if (options.onboarding && hasActivatedOnboardingPlan(ctx.workspace)) {
    return { error: "onboarding_plan_locked" };
  }

  const normalized = code.trim().toLowerCase();
  const promoCode = await PromoCode.findOne({ code: normalized });
  if (!promoCode) return { error: "promo_code_not_found" };
  if (promoCode.expiresAt && promoCode.expiresAt < new Date()) {
    return { error: "promo_code_expired" };
  }
  if (promoCode.revokedAt) return { error: "promo_code_revoked" };

  if (promoCode.type === "beta2mo") {
    const user = await User.findOne({ workosUserId: ctx.userId }).lean();
    if (!user?.betaParticipation?.recordedAt) {
      return { error: "not_eligible_beta_participant" };
    }
    if (user.betaPromoRedeemedAt) {
      return { error: "beta_promo_already_redeemed" };
    }

    // codesRedeemed + betaPromoRedeemedAt + the grant write must all succeed
    // or all fail together (a partial failure would leave the code marked
    // redeemed with no grant applied), so this runs inside one transaction —
    // this also makes the Workspace $ne guard below atomic under a race.
    const now = new Date();
    let result: RedeemPromoCodeResult = { error: "promo_code_already_redeemed" };
    const session = await mongoose.startSession();
    try {
      await session.withTransaction(async () => {
        const redeemResult = await Workspace.updateOne(
          { _id: ctx.workspace._id, codesRedeemed: { $ne: promoCode._id } },
          { $addToSet: { codesRedeemed: promoCode._id } },
          { session }
        );
        if (redeemResult.modifiedCount === 0) {
          result = { error: "promo_code_already_redeemed" };
          await session.abortTransaction();
          return;
        }

        const userUpdateResult = await User.updateOne(
          { workosUserId: ctx.userId, betaPromoRedeemedAt: null },
          { $set: { betaPromoRedeemedAt: now } },
          { session }
        );
        if (userUpdateResult.modifiedCount === 0) {
          result = { error: "beta_promo_already_redeemed" };
          await session.abortTransaction();
          return;
        }

        if (isEntitled(ctx.workspace)) {
          // Already entitled — never overwrite a live LS subscription's ls*
          // fields or truncate a still-active grant. Queue instead; consumed
          // by pendingGrantUpdate() at the workspace's next terminal-expiry
          // transition (webhook / lifecycle sweep / beta close).
          await Workspace.updateOne(
            { _id: ctx.workspace._id },
            {
              $set: {
                "pendingPromoGrant.grantMonths": BETA2MO_GRANT_MONTHS,
                "pendingPromoGrant.queuedAt": now,
                ...(options.onboarding ? { onboardingPlanSelection: "promo" } : {}),
              },
            },
            { session }
          );
          result = { ok: true, startsImmediately: false };
        } else {
          const expiresAt = new Date(now);
          expiresAt.setMonth(expiresAt.getMonth() + BETA2MO_GRANT_MONTHS);
          await grantPlan(ctx.workspace._id, { plan: "pro", expiresAt, session });
          if (options.onboarding) {
            await Workspace.updateOne(
              { _id: ctx.workspace._id },
              { $set: { onboardingPlanSelection: "promo" } },
              { session }
            );
          }
          result = { ok: true, startsImmediately: true };
        }
      });
    } finally {
      await session.endSession();
    }

    return result;
  }

  // $addToSet is naturally idempotent (adding the same id twice is a no-op),
  // so gating this write on { codesRedeemed: { $ne } } and checking
  // modifiedCount is both the "already redeemed" check AND the defense
  // against two concurrent redemptions of the same code. Run it BEFORE
  // grantPlan: granting first would let a plain sequential resubmit of an
  // already-used code re-run grantPlan and push planGrantExpiresAt further
  // out every time, even though the function ultimately returns
  // "already redeemed".
  const redeemResult = await Workspace.updateOne(
    { _id: ctx.workspace._id, codesRedeemed: { $ne: promoCode._id } },
    { $addToSet: { codesRedeemed: promoCode._id } }
  );
  if (redeemResult.modifiedCount === 0) {
    return { error: "promo_code_already_redeemed" };
  }

  let expiresAt: Date | null = null;
  if (promoCode.type === "yearly") {
    expiresAt = new Date();
    expiresAt.setFullYear(expiresAt.getFullYear() + 1);
  } else if (promoCode.type === "monthly") {
    expiresAt = new Date();
    expiresAt.setMonth(expiresAt.getMonth() + 1);
  }
  const plan = promoCode.type === "beta" ? "beta" : "pro";
  await grantPlan(ctx.workspace._id, { plan, expiresAt });
  if (options.onboarding) {
    await Workspace.updateOne(
      { _id: ctx.workspace._id },
      { $set: { onboardingPlanSelection: "promo" } }
    );
  }

  return { ok: true, startsImmediately: true };
}
